const brazilianCities = [
  "São Paulo",
  "Rio de Janeiro",
  "Brasília",
  "Salvador",
  "Fortaleza",
  "Belo Horizonte",
  "Manaus",
  "Curitiba",
  "Recife",
  "Goiânia",
  "Belém",
  "Porto Alegre",
  "Guarulhos",
  "Campinas",
  "São Luís",
  "São Gonçalo",
  "Maceió",
  "Duque de Caxias",
  "Campo Grande",
  "Natal",
  "Teresina",
  "João Pessoa",
  "São Bernardo do Campo",
  "Osasco",
  "Santo André",
  "Uberlândia",
  "Sorocaba",
  "Ribeirão Preto",
  "Contagem",
  "Aracaju",
  "Feira de Santana",
  "Joinville",
  "Londrina",
  "Juiz de Fora",
  "Niterói",
  "Ananindeua",
  "Serra",
  "Cuiabá",
  "Aparecida de Goiânia",
  "Caxias do Sul",
  "Porto Velho",
  "Belford Roxo",
  "Campos dos Goytacazes",
  "Florianópolis",
  "Vila Velha",
  "São João de Meriti",
  "Macapá",
  "São José do Rio Preto",
  "Mogi das Cruzes",
  "Diadema",
  "Betim",
  "Jundiaí",
  "Maringá",
  "Rio Branco",
  "Montes Claros",
  "Piracicaba",
  "Carapicuíba",
  "Olinda",
  "Cariacica",
  "Bauru",
  "Vitória",
  "Blumenau",
  "Franca",
  "Pelo Santo", 
  "Boa Vista",
  "Parnamirim",
  "São Vicente",
  "Caucaia",
  "Itaquaquecetuba",
  "Foz do Iguaçu",
  "Limeira",
  "Petrópolis",
  "Pelotas",
  "Vitória da Conquista",
  "Suzano",
  "Santarém",
  "Taboão da Serra",
  "Sumaré",
  "Governador Valadares",
  "Gravataí",
  "Barueri",
  "Várzea Grande",
  "Embu das Artes",
  "Ponta Grossa",
  "Santa Maria",
  "Barreiras",
  "Cascavel",
  "Novo Hamburgo",
  "Volta Redonda",
  "Ipatinga",
  "Presidente Prudente",
  "Uberaba",
  "Viana",
  "Ribeirão das Neves",
  "Colombo",
  "Magé",
  "Alvorada",
  "Votorantim",
  "Araçatuba",
  "Atibaia",
  "Pindamonhangaba",
  "Jaú",
  "Indaiatuba",
  "São Carlos",
  "Cotia",
  "Valparaíso de Goiás",
  "Itabuna",
  "São José dos Pinhais",
  "Nova Iguaçu"
];

export default brazilianCities;